insert into regioni (id,nome,sigla) values
 (10, 'Piemonte', 'PIE')
,(20, 'Valle d''Aosta', 'VDA')
,(30, 'Lombardia', 'LOM')
,(40, 'Trentino-Alto Adige', 'TAA')
-- ,(41, 'Provincia Autonoma Bolzano', 'PAB')
-- ,(42, 'Provincia Autonoma Trento', 'PAT')
,(50, 'Veneto', 'VEN')
,(60, 'Friuli-Venezia Giulia', 'FVG')
,(70, 'Liguria', 'LIG')
,(80, 'Emilia-Romagna', 'EMR')
,(90, 'Toscana', 'TOS')
,(100, 'Umbria', 'UMB')
,(110, 'Marche', 'MAR')
,(120, 'Lazio', 'LAZ')
,(130, 'Abruzzo', 'ABR')
,(140, 'Molise', 'MOL')
,(150, 'Campania', 'CAM')
,(160, 'Puglia', 'PUL')
,(170, 'Basilicata', 'BAS')
,(180, 'Calabria', 'CAL')
,(190, 'Sicilia', 'SIC')
,(200, 'Sardegna', 'SAR')
;

commit;
