insert into  nations (alpha3_cod, alpha2_cod, name, nat_phone_prefix, curr_code, continent, languages) values
('AFG','AF','AFGHANISTAN','+93','AFN','AS','fa-AF,ps,uz-AF,tk'),
('ALB','AL','ALBANIA','+355','ALL','EU','sq,el'),
('DZA','DZ','ALGERIA','+213','DZD','AF','ar-DZ'),
('ASM','AS','AMERICAN SAMOA','+1-684','USD','OC','en-AS,sm,to'),
('AND','AD','ANDORRA','+376','EUR','EU','ca'),
('AGO','AO','ANGOLA','+244','AOA','AF','pt-AO'),
('AIA','AI','ANGUILLA','+1-264','XCD','NA','en-AI'),
('ATA','AQ','ANTARCTICA','+672','','AN',''),
('ATG','AG','ANTIGUA AND BARBUDA','+1-268','XCD','NA','en-AG'),
('ARG','AR','ARGENTINA','+54','ARS','SA','es-AR,en,it,de,fr,gn'),
('ARM','AM','ARMENIA','+374','AMD','AS','hy'),
('ABW','AW','ARUBA','+297','AWG','NA','nl-AW,es,en'),
('AUS','AU','AUSTRALIA','+61','AUD','OC','en-AU'),
('AUT','AT','AUSTRIA','+43','EUR','EU','de-AT,hr,hu,sl'),
('AZE','AZ','AZERBAIJAN','+994','AZN','AS','az,ru,hy'),
('BHS','BS','BAHAMAS','+1-242','BSD','NA','en-BS'),
('BHR','BH','BAHRAIN','+973','BHD','AS','ar-BH,en,fa,ur'),
('BGD','BD','BANGLADESH','+880','BDT','AS','bn-BD,en'),
('BRB','BB','BARBADOS','+1-246','BBD','NA','en-BB'),
('BLR','BY','BELARUS','+375','BYR','EU','be,ru'),
('BEL','BE','BELGIUM','+32','EUR','EU','nl-BE,fr-BE,de-BE'),
('BLZ','BZ','BELIZE','+501','BZD','NA','en-BZ,es'),
('BEN','BJ','BENIN','+229','XOF','AF','fr-BJ'),
('BMU','BM','BERMUDA','+1-441','BMD','NA','en-BM,pt'),
('BTN','BT','BHUTAN','+975','INR','AS','dz'),
('BOL','BO','BOLIVIA, PLURINATIONAL STATE OF','+591','BOB','SA','es-BO,qu,ay'),
('BIH','BA','BOSNIA AND HERZEGOVINA','+387','BAM','EU','bs,hr-BA,sr-BA'),
('BWA','BW','BOTSWANA','+267','BWP','AF','en-BW,tn-BW'),
('BVT','BV','BOUVET ISLAND','+47','','AN',''),
('BRA','BR','BRAZIL','+55','BRL','SA','pt-BR,es,en,fr'),
('IOT','IO','BRITISH INDIAN OCEAN TERRITORY','+246','','AS','en-IO'),
('VGB','VG','VIRGIN ISLANDS (BRITISH)','+1-284','USD','NA','en-VG'),
('BRN','BN','BRUNEI DARUSSALAM','+673','BND','AS','ms-BN,en-BN'),
('BGR','BG','BULGARIA','+359','BGN','EU','bg,tr-BG,rom'),
('BFA','BF','BURKINA FASO','+226','XOF','AF','fr-BF'),
('BDI','BI','BURUNDI','+257','BIF','AF','fr-BI,rn'),
('KHM','KH','CAMBODIA','+855','KHR','AS','km,fr,en'),
('CMR','CM','CAMEROON','+237','XAF','AF','en-CM,fr-CM'),
('CAN','CA','CANADA','+1','CAD','NA','en-CA,fr-CA,iu'),
('CPV','CV','CABO VERDE','+238','CVE','AF','pt-CV'),
('BES','BQ','BONAIRE, SINT EUSTATIUS AND SABA','+599','USD','NA','nl,pap,en'),
('CYM','KY','CAYMAN ISLANDS','+1-345','KYD','NA','en-KY'),
('CAF','CF','CENTRAL AFRICAN REPUBLIC','+236','XAF','AF','fr-CF,sg,ln,kg'),
('TCD','TD','CHAD','+235','XAF','AF','fr-TD,ar-TD,sre'),
('CHL','CL','CHILE','+56','CLP','SA','es-CL'),
('CHN','CN','CHINA','+86','CNY','AS','zh-CN,yue,wuu,dta,ug,za'),
('CXR','CX','CHRISTMAS ISLAND','+61','','AS','en,zh,ms-CC'),
('CCK','CC','COCOS (KEELING) ISLANDS','+61','','AS','ms-CC,en'),
('COL','CO','COLOMBIA','+57','COP','SA','es-CO'),
('COM','KM','COMOROS','+269','KMF','AF','ar,fr-KM'),
('COG','CG','CONGO','+242','XAF','AF','fr-CG,kg,ln-CG'),
('COD','CD','CONGO - KINSHASA','+243','','AF','fr-CD,ln,kg'),
('COK','CK','COOK ISLANDS','+682','NZD','OC','en-CK,mi'),
('CRI','CR','COSTA RICA','+506','CRC','NA','es-CR,en'),
('HRV','HR','CROATIA','+385','HRK','EU','hr-HR,sr'),
('CUB','CU','CUBA','+53','CUP','NA','es-CU'),
('CUW','CW','CURAÇAO','+599','ANG','NA','nl,pap'),
('CYP','CY','CYPRUS','+357','EUR','EU','el-CY,tr-CY,en'),
('CZE','CZ','CZECH REPUBLIC','+420','','EU','cs,sk'),
('CIV','CI','CÔTE D`IVOIRE','+225','XOF','AF','fr-CI'),
('DNK','DK','DENMARK','+45','DKK','EU','da-DK,en,fo,de-DK'),
('DJI','DJ','DJIBOUTI','+253','DJF','AF','fr-DJ,ar,so-DJ,aa'),
('DMA','DM','DOMINICA','+1-767','XCD','NA','en-DM'),
('DOM','DO','DOMINICAN REPUBLIC','+1-809,1-829,1-849','DOP','NA','es-DO'),
('ECU','EC','ECUADOR','+593','USD','SA','es-EC'),
('EGY','EG','EGYPT','+20','EGP','AF','ar-EG,en,fr'),
('SLV','SV','EL SALVADOR','+503','USD','NA','es-SV'),
('GNQ','GQ','EQUATORIAL GUINEA','+240','XAF','AF','es-GQ,fr'),
('ERI','ER','ERITREA','+291','ERN','AF','aa-ER,ar,tig,kun,ti-ER'),
('EST','EE','ESTONIA','+372','EUR','EU','et,ru'),
('ETH','ET','ETHIOPIA','+251','ETB','AF','am,en-ET,om-ET,ti-ET,so-ET,sid'),
('FLK','FK','FALKLAND ISLANDS (MALVINAS)','+500','FKP','SA','en-FK'),
('FRO','FO','FAROE ISLANDS','+298','','EU','fo,da-FO'),
('FJI','FJ','FIJI','+679','FJD','OC','en-FJ,fj'),
('FIN','FI','FINLAND','+358','EUR','EU','fi-FI,sv-FI,smn'),
('FRA','FR','FRANCE','+33','EUR','EU','fr-FR,frp,br,co,ca,eu,oc'),
('GUF','GF','FRENCH GUIANA','+594','EUR','SA','fr-GF'),
('PYF','PF','FRENCH POLYNESIA','+689','XPF','OC','fr-PF,ty'),
('ATF','TF','FRENCH SOUTHERN TERRITORIES','+262','','AN','fr'),
('GAB','GA','GABON','+241','XAF','AF','fr-GA'),
('GMB','GM','GAMBIA','+220','GMD','AF','en-GM,mnk,wof,wo,ff'),
('GEO','GE','GEORGIA','+995','GEL','AS','ka,ru,hy,az'),
('DEU','DE','GERMANY','+49','EUR','EU','de'),
('GHA','GH','GHANA','+233','GHS','AF','en-GH,ak,ee,tw'),
('GIB','GI','GIBRALTAR','+350','GIP','EU','en-GI,es,it,pt'),
('GRC','GR','GREECE','+30','EUR','EU','el-GR,en,fr'),
('GRL','GL','GREENLAND','+299','DKK','NA','kl,da-GL,en'),
('GRD','GD','GRENADA','+1-473','XCD','NA','en-GD'),
('GLP','GP','GUADELOUPE','+590','EUR','NA','fr-GP'),
('GUM','GU','GUAM','+1-671','USD','OC','en-GU,ch-GU'),
('GTM','GT','GUATEMALA','+502','GTQ','NA','es-GT'),
('GGY','GG','GUERNSEY','+44','GBP','EU','en,fr'),
('GIN','GN','GUINEA','+224','GNF','AF','fr-GN'),
('GNB','GW','GUINEA-BISSAU','+245','XOF','AF','pt-GW,pov'),
('GUY','GY','GUYANA','+592','GYD','SA','en-GY'),
('HTI','HT','HAITI','+509','USD','NA','ht,fr-HT'),
('HMD','HM','HEARD & MCDONALD ISLANDS','+672','','AN',''),
('HND','HN','HONDURAS','+504','HNL','NA','es-HN'),
('HKG','HK','HONG KONG','+852','','AS','zh-HK,yue,zh,en'),
('HUN','HU','HUNGARY','+36','HUF','EU','hu-HU'),
('ISL','IS','ICELAND','+354','ISK','EU','is,en,de,da,sv,no'),
('IND','IN','INDIA','+91','INR','AS','en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc'),
('IDN','ID','INDONESIA','+62','IDR','AS','id,en,nl,jv'),
('IRN','IR','IRAN, ISLAMIC REPUBLIC OF','+98','IRR','AS','fa-IR,ku'),
('IRQ','IQ','IRAQ','+964','IQD','AS','ar-IQ,ku,hy'),
('IRL','IE','IRELAND','+353','EUR','EU','en-IE,ga-IE'),
('IMN','IM','ISLE OF MAN','+44','GBP','EU','en,gv'),
('ISR','IL','ISRAEL','+972','ILS','AS','he,ar-IL,en-IL,'),
('ITA','IT','ITALY','+39','EUR','EU','it-IT,de-IT,fr-IT,sc,ca,co,sl'),
('JAM','JM','JAMAICA','+1-876','JMD','NA','en-JM'),
('JPN','JP','JAPAN','+81','JPY','AS','ja'),
('JEY','JE','JERSEY','+44','GBP','EU','en,pt'),
('JOR','JO','JORDAN','+962','JOD','AS','ar-JO,en'),
('KAZ','KZ','KAZAKHSTAN','+7','KZT','AS','kk,ru'),
('KEN','KE','KENYA','+254','KES','AF','en-KE,sw-KE'),
('KIR','KI','KIRIBATI','+686','AUD','OC','en-KI,gil'),
('XKS','XK','Kosovo','+383','EUR','EU','sq,sr'),
('KWT','KW','KUWAIT','+965','KWD','AS','ar-KW,en'),
('KGZ','KG','KYRGYZSTAN','+996','KGS','AS','ky,uz,ru'),
('LAO','LA','LAO PEOPLEâ€™S DEMOCRATIC REPUBLIC','+856','LAK','AS','lo,fr,en'),
('LVA','LV','LATVIA','+371','EUR','EU','lv,ru,lt'),
('LBN','LB','LEBANON','+961','LBP','AS','ar-LB,fr-LB,en,hy'),
('LSO','LS','LESOTHO','+266','ZAR','AF','en-LS,st,zu,xh'),
('LBR','LR','LIBERIA','+231','LRD','AF','en-LR'),
('LBY','LY','LIBYA','+218','LYD','AF','ar-LY,it,en'),
('LIE','LI','LIECHTENSTEIN','+423','CHF','EU','de-LI'),
('LTU','LT','LITHUANIA','+370','EUR','EU','lt,ru,pl'),
('LUX','LU','LUXEMBOURG','+352','EUR','EU','lb,de-LU,fr-LU'),
('MAC','MO','MACAO','+853','MOP','AS','zh,zh-MO,pt'),
('MKD','MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','+389','MKD','EU','mk,sq,tr,rmm,sr'),
('MDG','MG','MADAGASCAR','+261','MGA','AF','fr-MG,mg'),
('MWI','MW','MALAWI','+265','MWK','AF','ny,yao,tum,swk'),
('MYS','MY','MALAYSIA','+60','MYR','AS','ms-MY,en,zh,ta,te,ml,pa,th'),
('MDV','MV','MALDIVES','+960','MVR','AS','dv,en'),
('MLI','ML','MALI','+223','XOF','AF','fr-ML,bm'),
('MLT','MT','MALTA','+356','EUR','EU','mt,en-MT'),
('MHL','MH','MARSHALL ISLANDS','+692','USD','OC','mh,en-MH'),
('MTQ','MQ','MARTINIQUE','+596','EUR','NA','fr-MQ'),
('MRT','MR','MAURITANIA','+222','MRO','AF','ar-MR,fuc,snk,fr,mey,wo'),
('MUS','MU','MAURITIUS','+230','MUR','AF','en-MU,bho,fr'),
('MYT','YT','MAYOTTE','+262','EUR','AF','fr-YT'),
('MEX','MX','MEXICO','+52','MXN','NA','es-MX'),
('FSM','FM','MICRONESIA, FEDERATED STATES OF','+691','USD','OC','en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg'),
('MDA','MD','MOLDOVA, REPUBLIC OF','+373','MDL','EU','ro,ru,gag,tr'),
('MCO','MC','MONACO','+377','EUR','EU','fr-MC,en,it'),
('MNG','MN','MONGOLIA','+976','MNT','AS','mn,ru'),
('MNE','ME','MONTENEGRO','+382','EUR','EU','sr,hu,bs,sq,hr,rom'),
('MSR','MS','MONTSERRAT','+1-664','XCD','NA','en-MS'),
('MAR','MA','MOROCCO','+212','MAD','AF','ar-MA,ber,fr'),
('MOZ','MZ','MOZAMBIQUE','+258','MZN','AF','pt-MZ,vmw'),
('MMR','MM','MYANMAR','+95','MMK','AS','my'),
('NAM','NA','NAMIBIA','+264','ZAR','AF','en-NA,af,de,hz,naq'),
('NRU','NR','NAURU','+674','AUD','OC','na,en-NR'),
('NPL','NP','NEPAL','+977','NPR','AS','ne,en'),
('NLD','NL','NETHERLANDS','+31','EUR','EU','nl-NL,fy-NL'),
('NCL','NC','NEW CALEDONIA','+687','XPF','OC','fr-NC'),
('NZL','NZ','NEW ZEALAND','+64','NZD','OC','en-NZ,mi'),
('NIC','NI','NICARAGUA','+505','NIO','NA','es-NI,en'),
('NER','NE','NIGER','+227','XOF','AF','fr-NE,ha,kr,dje'),
('NGA','NG','NIGERIA','+234','NGN','AF','en-NG,ha,yo,ig,ff'),
('NIU','NU','NIUE','+683','NZD','OC','niu,en-NU'),
('NFK','NF','NORFOLK ISLAND','+672','AUD','OC','en-NF'),
('PRK','KP','KOREA, DEMOCRATIC PEOPLEâ€™S REPUBLIC OF','+850','KPW','AS','ko-KP'),
('MNP','MP','NORTHERN MARIANA ISLANDS','+1-670','USD','OC','fil,tl,zh,ch-MP,en-MP'),
('NOR','NO','NORWAY','+47','NOK','EU','no,nb,nn,se,fi'),
('OMN','OM','OMAN','+968','OMR','AS','ar-OM,en,bal,ur'),
('PAK','PK','PAKISTAN','+92','PKR','AS','ur-PK,en-PK,pa,sd,ps,brh'),
('PLW','PW','PALAU','+680','USD','OC','pau,sov,en-PW,tox,ja,fil,zh'),
('PSE','PS','PALESTINE, STATE OF','+970','','AS','ar-PS'),
('PAN','PA','PANAMA','+507','USD','NA','es-PA,en'),
('PNG','PG','PAPUA NEW GUINEA','+675','PGK','OC','en-PG,ho,meu,tpi'),
('PRY','PY','PARAGUAY','+595','PYG','SA','es-PY,gn'),
('PER','PE','PERU','+51','PEN','SA','es-PE,qu,ay'),
('PHL','PH','PHILIPPINES','+63','PHP','AS','tl,en-PH,fil'),
('PCN','PN','PITCAIRN','+870','NZD','OC','en-PN'),
('POL','PL','POLAND','+48','PLN','EU','pl'),
('PRT','PT','PORTUGAL','+351','EUR','EU','pt-PT,mwl'),
('PRI','PR','PUERTO RICO','+1','USD','NA','en-PR,es-PR'),
('QAT','QA','QATAR','+974','QAR','AS','ar-QA,es'),
('ROU','RO','ROMANIA','+40','RON','EU','ro,hu,rom'),
('RUS','RU','RUSSIAN FEDERATION','+7','RUB','EU','ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog'),
('RWA','RW','RWANDA','+250','RWF','AF','rw,en-RW,fr-RW,sw'),
('REU','RE','RÉUNION','+262','EUR','AF','fr-RE'),
('WSM','WS','SAMOA','+685','WST','OC','sm,en-WS'),
('SMR','SM','SAN MARINO','+378','EUR','EU','it-SM'),
('SAU','SA','SAUDI ARABIA','+966','SAR','AS','ar-SA'),
('SEN','SN','SENEGAL','+221','XOF','AF','fr-SN,wo,fuc,mnk'),
('SRB','RS','SERBIA','+381 p','RSD','EU','sr,hu,bs,rom'),
('SYC','SC','SEYCHELLES','+248','SCR','AF','en-SC,fr-SC'),
('SLE','SL','SIERRA LEONE','+232','SLL','AF','en-SL,men,tem'),
('SGP','SG','SINGAPORE','+65','SGD','AS','cmn,en-SG,ms-SG,ta-SG,zh-SG'),
('SXM','SX','SINT MAARTEN (DUTCH PART)','+1-721','ANG','NA','nl,en'),
('SVK','SK','SLOVAKIA','+421','EUR','EU','sk,hu'),
('SVN','SI','SLOVENIA','+386','EUR','EU','sl,sh'),
('SLB','SB','SOLOMON ISLANDS','+677','SBD','OC','en-SB,tpi'),
('SOM','SO','SOMALIA','+252','SOS','AF','so-SO,ar-SO,it,en-SO'),
('ZAF','ZA','SOUTH AFRICA','+27','ZAR','AF','zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr'),
('SGS','GS','SOUTH GEORGIA & SOUTH SANDWICH ISLANDS','+500','','AN','en'),
('KOR','KR','KOREA, REPUBLIC OF','+82','KRW','AS','ko-KR,en'),
('SSD','SS','SOUTH SUDAN','+211','SSP','AF','en'),
('ESP','ES','SPAIN','+34','EUR','EU','es-ES,ca,gl,eu,oc'),
('LKA','LK','SRI LANKA','+94','LKR','AS','si,ta,en'),
('BLM','BL','SAINT BARTHÃ‰LEMY','+590','EUR','NA','fr'),
('SHN','SH','SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','+290 n','SHP','AF','en-SH'),
('KNA','KN','SAINT KITTS AND NEVIS','+1-869','XCD','NA','en-KN'),
('LCA','LC','SAINT LUCIA','+1-758','XCD','NA','en-LC'),
('MAF','MF','SAINT MARTIN (FRENCH PART)','+590','EUR','NA','fr'),
('SPM','PM','SAINT PIERRE AND MIQUELON','+508','EUR','NA','fr-PM'),
('VCT','VC','SAINT VINCENT AND THE GRENADINES','+1-784','XCD','NA','en-VC,fr'),
('SDN','SD','SUDAN','+249','SDG','AF','ar-SD,en,fia'),
('SUR','SR','SURINAME','+597','SRD','SA','nl-SR,en,srn,hns,jv'),
('SJM','SJ','SVALBARD AND JAN MAYEN','+47','NOK','EU','no,ru'),
('SWZ','SZ','SWAZILAND','+268','SZL','AF','en-SZ,ss-SZ'),
('SWE','SE','SWEDEN','+46','SEK','EU','sv-SE,se,sma,fi-SE'),
('CHE','CH','SWITZERLAND','+41','CHF','EU','de-CH,fr-CH,it-CH,rm'),
('SYR','SY','SYRIAN ARAB REPUBLIC','+963','SYP','AS','ar-SY,ku,hy,arc,fr,en'),
('STP','ST','SAO TOME AND PRINCIPE','+239','STD','AF','pt-ST'),
('TWN','TW','TAIWAN','+886','','AS','zh-TW,zh,nan,hak'),
('TJK','TJ','TAJIKISTAN','+992','TJS','AS','tg,ru'),
('TZA','TZ','TANZANIA, UNITED REPUBLIC OF','+255','TZS','AF','sw-TZ,en,ar'),
('THA','TH','THAILAND','+66','THB','AS','th,en'),
('TLS','TL','TIMOR-LESTE','+670','USD','OC','tet,pt-TL,id,en'),
('TGO','TG','TOGO','+228','XOF','AF','fr-TG,ee,hna,kbp,dag,ha'),
('TKL','TK','TOKELAU','+690','NZD','OC','tkl,en-TK'),
('TON','TO','TONGA','+676','TOP','OC','to,en-TO'),
('TTO','TT','TRINIDAD AND TOBAGO','+1-868','TTD','NA','en-TT,hns,fr,es,zh'),
('TUN','TN','TUNISIA','+216','TND','AF','ar-TN,fr'),
('TUR','TR','TURKEY','+90','TRY','AS','tr-TR,ku,diq,az,av'),
('TKM','TM','TURKMENISTAN','+993','TMT','AS','tk,ru,uz'),
('TCA','TC','TURKS AND CAICOS ISLANDS','+1-649','USD','NA','en-TC'),
('TUV','TV','TUVALU','+688','AUD','OC','tvl,en,sm,gil'),
('UMI','UM','U.S. OUTLYING ISLANDS','+None','','OC','en-UM'),
('VIR','VI','VIRGIN ISLANDS (U.S.)','+1-340','USD','NA','en-VI'),
('GBR','GB','UNITED KINGDOM','+44','GBP','EU','en-GB,cy-GB,gd'),
('USA','US','UNITED STATES','+1','USD','NA','en-US,es-US,haw,fr'),
('UGA','UG','UGANDA','+256','UGX','AF','en-UG,lg,sw,ar'),
('UKR','UA','UKRAINE','+380','UAH','EU','uk,ru-UA,rom,pl,hu'),
('ARE','AE','UNITED ARAB EMIRATES','+971','AED','AS','ar-AE,fa,en,hi,ur'),
('URY','UY','URUGUAY','+598','UYU','SA','es-UY'),
('UZB','UZ','UZBEKISTAN','+998','UZS','AS','uz,ru,tg'),
('VUT','VU','VANUATU','+678','VUV','OC','bi,en-VU,fr-VU'),
('VAT','VA','HOLY SEE (VATICAN CITY STATE)','+39-06','EUR','EU','la,it,fr'),
('VEN','VE','VENEZUELA, BOLIVARIAN REPUBLIC OF','+58','VEF','SA','es-VE'),
('VNM','VN','VIET NAM','+84','VND','AS','vi,en,fr,zh,km'),
('WLF','WF','WALLIS AND FUTUNA','+681','XPF','OC','wls,fud,fr-WF'),
('ESH','EH','WESTERN SAHARA','+212','MAD','AF','ar,mey'),
('YEM','YE','YEMEN','+967','YER','AS','ar-YE'),
('ZMB','ZM','ZAMBIA','+260','ZMW','AF','en-ZM,bem,loz,lun,lue,ny,toi'),
('ZWE','ZW','ZIMBABWE','+263','ZWL','AF','en-ZW,sn,nr,nd'),
('ALA','AX','ÃLAND ISLANDS','+358','EUR','EU','sv-AX');